### ISSUE TITLE
Description of options makes no sense

### ISSUE THREAD

**Issue by andrewferrier** [vladdoster/remember.nvim#2]
The description of each option in the docs makes no sense, and appears to have maybe been lifted from another plugin?

For example, see https://github.com/vladdoster/remember.nvim/blob/master/doc/remember.txt#L31

**Comment by vladdoster** [comment]
@andrewferrier Good catch. Indeed copied from somewhere ([barber](https://github.com/romgrk/barbar.nvim) from a quick google search) to get the format correct (my first time writing vim documentation).

Fixing now

**Comment by vladdoster** [comment]
@andrewferrier Addressed in [v1.2.1](https://github.com/vladdoster/remember.nvim/compare/v1.2.0...v1.2.1).

Thanks for taking the time to report this issue :)
